export const REGISTER_EMPLOYEE_ERROR = "REGISTER_EMPLOYEE_ERROR";
export const FETCH_EMPLOYEE_REPORT = "FETCH_EMPLOYEE_REPORT"
export const FETCH_SINGLE_EMPLOYEE = "FETCH_SINGLE_EMPLOYEE";
export const FETCH_GETBYIDEMPLOYEE_SUCCESS = "FETCH_GETBYIDEMPLOYEE_SUCCESS";
export const FETCH_EMPLOYEESTOASSIGN_SUCCESS ="FETCH_EMPLOYEESTOASSIGN_SUCCESS";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const GET_EMPLOYEE__SUCCESS = "GET_EMPLOYEE__SUCCESS";
export const REGISTER_EMPLOYEE_SUCCESS = "REGISTER_EMPLOYEE_SUCCESS";
export const REGISTER_USER = "REGISTER_USER";
export const GET_ALL_USER = "GET_ALL_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const FETCH_SINGLE_DISTRICT = "FETCH_SINGLE_DISTRICT";
export const FETCH_WORKING_HOURS = "FETCH_WORKING_HOURS";
export const FETCH_ALL_DISTRICTS = "FETCH_ALL_DISTRICTS";
export const FETCH_SELECTED_STATE = "FETCH_SELECTED_STATE";
export const FETCH_NATIONAL_ID = "FETCH_NATIONAL_ID";
export const FETCH_UNAVAILABLE_HOURS = "FETCH_UNAVAILABLE_HOURS";
export const FETCH_AVAILABLE_DATES = "FETCH_AVAILABLE_DATES";
export const FETCH_AVAILABLE_DATES_ERROR = "FETCH_AVAILABLE_DATES_ERROR";

//applicants
export const FETCH_UNAPPROVED_APPLICANTS = "FETCH_UNAPPROVED_APPLICANTS";
export const UNAPPROVED_APPLICANTS = "UNAPPROVED_APPLICANTS";
export const FETCH_APPROVED_APPLICANTS = "FETCH_APPROVED_APPLICANTS";
export const FETCH_DISTRICT_HOLYDAYS = "FETCH_DISTRICT_HOLYDAYS";
export const FETCH_APPLICANT_IMAGE = "FETCH_APPLICANT_IMAGE";
export const FETCH_APPOINTMENT = "FETCH_APPOINTMENT";


// users
